const Screens = {
    SPLASH: 'SplashScreen',
    LOADING: 'LoadingScreen',
    LANDING: 'Landingscreen',
    SIGN_UP: 'SignUp',
    SIGN_IN: 'SignIn',
    HOME: 'Homepage',
    DETAIL_VIEW: 'DetailView',
    ARTICLE_PAGE: 'Infopage',
    MAP: 'Map',
    PROFILE: 'Profile',
    CONTACT_US: 'ContactUs',
    DATA_POLICY: 'DataPolicy',
    MY_DRAFTS: 'MyDrafts',
    MY_SETTINGS: 'MySettings',
    CHANGE_PASSWORD: 'ChangePassword',
    DELETE_ACCOUNT: 'DeleteAccount',
    ACCOUNT_SETTINGS: 'AccountSettings',
    NOTIFICATIONS: 'Notifications',
    TERMS_AND_CONDITIONS: 'TermsAndConditions',
    PROFILE_CREATED: 'ProfileCreated',
    STATS_INFO: 'StatsInfo',
    VISITED_UPTAINER_STAT: 'VisitedUptainerStat',
    STATS: 'Stats',
    YOUR_STATS: 'YourStats',
    ADD: 'Add',
    TAKE_QR_SCANNER: 'TakeQRScanner',
    ADD_QR_SCANNER: 'AddQRScanner',
    PRODUCTS: 'Products',
    PRO: 'Pro',
    BND: 'Bnd',
    MOD: 'Mod',
    STATIONS: 'Stations',
    STATION_DETAILS: 'StationDetails',
    THANKS: 'Thanks',
    LOGOUT_CONFIRMATION: 'LogoutConfirmation',
    PRIVACY_POLICY: 'PrivacyPolicy',
    UPTAINER_DETAILS: 'UptainerDetails',
    PRODUCT_SAVED: 'ProductSaved',
    PRODUCT_IS_TAKEN: 'ProductIsTakenScreen',
    PRODUCT_TAKEN: 'ProductTaken',
    THANK_YOU: 'ThankYouScreen',
    CAMERA: 'Camera',
    FORGOT_PASSWORD: 'ForgotPassword',
  };
  
  export default Screens;
  
